// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/log_entry.proto

package dev.bytekv.proto;

public final class LogEntryOuterClass {
  private LogEntryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.bytekv.proto.LogEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 serialNum = 1;</code>
     * @return The serialNum.
     */
    long getSerialNum();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string operation = 3;</code>
     * @return The operation.
     */
    java.lang.String getOperation();
    /**
     * <code>string operation = 3;</code>
     * @return The bytes for operation.
     */
    com.google.protobuf.ByteString
        getOperationBytes();

    /**
     * <code>string key = 4;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 4;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 5;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 5;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>bool isTTL = 6;</code>
     * @return The isTTL.
     */
    boolean getIsTTL();

    /**
     * <code>int64 expiryTime = 7;</code>
     * @return The expiryTime.
     */
    long getExpiryTime();
  }
  /**
   * Protobuf type {@code dev.bytekv.proto.LogEntry}
   */
  public static final class LogEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.bytekv.proto.LogEntry)
      LogEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogEntry.newBuilder() to construct.
    private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntry() {
      operation_ = "";
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.bytekv.proto.LogEntryOuterClass.internal_static_dev_bytekv_proto_LogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.bytekv.proto.LogEntryOuterClass.internal_static_dev_bytekv_proto_LogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.bytekv.proto.LogEntryOuterClass.LogEntry.class, dev.bytekv.proto.LogEntryOuterClass.LogEntry.Builder.class);
    }

    public static final int SERIALNUM_FIELD_NUMBER = 1;
    private long serialNum_;
    /**
     * <code>int64 serialNum = 1;</code>
     * @return The serialNum.
     */
    @java.lang.Override
    public long getSerialNum() {
      return serialNum_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int OPERATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object operation_;
    /**
     * <code>string operation = 3;</code>
     * @return The operation.
     */
    @java.lang.Override
    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operation_ = s;
        return s;
      }
    }
    /**
     * <code>string operation = 3;</code>
     * @return The bytes for operation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 4;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 4;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 5;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISTTL_FIELD_NUMBER = 6;
    private boolean isTTL_;
    /**
     * <code>bool isTTL = 6;</code>
     * @return The isTTL.
     */
    @java.lang.Override
    public boolean getIsTTL() {
      return isTTL_;
    }

    public static final int EXPIRYTIME_FIELD_NUMBER = 7;
    private long expiryTime_;
    /**
     * <code>int64 expiryTime = 7;</code>
     * @return The expiryTime.
     */
    @java.lang.Override
    public long getExpiryTime() {
      return expiryTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serialNum_ != 0L) {
        output.writeInt64(1, serialNum_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, operation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
      }
      if (isTTL_ != false) {
        output.writeBool(6, isTTL_);
      }
      if (expiryTime_ != 0L) {
        output.writeInt64(7, expiryTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serialNum_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, operation_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
      }
      if (isTTL_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isTTL_);
      }
      if (expiryTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, expiryTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.bytekv.proto.LogEntryOuterClass.LogEntry)) {
        return super.equals(obj);
      }
      dev.bytekv.proto.LogEntryOuterClass.LogEntry other = (dev.bytekv.proto.LogEntryOuterClass.LogEntry) obj;

      if (getSerialNum()
          != other.getSerialNum()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getOperation()
          .equals(other.getOperation())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getIsTTL()
          != other.getIsTTL()) return false;
      if (getExpiryTime()
          != other.getExpiryTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALNUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSerialNum());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + ISTTL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTTL());
      hash = (37 * hash) + EXPIRYTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpiryTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.bytekv.proto.LogEntryOuterClass.LogEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.bytekv.proto.LogEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.bytekv.proto.LogEntry)
        dev.bytekv.proto.LogEntryOuterClass.LogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.bytekv.proto.LogEntryOuterClass.internal_static_dev_bytekv_proto_LogEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.bytekv.proto.LogEntryOuterClass.internal_static_dev_bytekv_proto_LogEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.bytekv.proto.LogEntryOuterClass.LogEntry.class, dev.bytekv.proto.LogEntryOuterClass.LogEntry.Builder.class);
      }

      // Construct using dev.bytekv.proto.LogEntryOuterClass.LogEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serialNum_ = 0L;

        timestamp_ = 0L;

        operation_ = "";

        key_ = "";

        value_ = "";

        isTTL_ = false;

        expiryTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.bytekv.proto.LogEntryOuterClass.internal_static_dev_bytekv_proto_LogEntry_descriptor;
      }

      @java.lang.Override
      public dev.bytekv.proto.LogEntryOuterClass.LogEntry getDefaultInstanceForType() {
        return dev.bytekv.proto.LogEntryOuterClass.LogEntry.getDefaultInstance();
      }

      @java.lang.Override
      public dev.bytekv.proto.LogEntryOuterClass.LogEntry build() {
        dev.bytekv.proto.LogEntryOuterClass.LogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.bytekv.proto.LogEntryOuterClass.LogEntry buildPartial() {
        dev.bytekv.proto.LogEntryOuterClass.LogEntry result = new dev.bytekv.proto.LogEntryOuterClass.LogEntry(this);
        result.serialNum_ = serialNum_;
        result.timestamp_ = timestamp_;
        result.operation_ = operation_;
        result.key_ = key_;
        result.value_ = value_;
        result.isTTL_ = isTTL_;
        result.expiryTime_ = expiryTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.bytekv.proto.LogEntryOuterClass.LogEntry) {
          return mergeFrom((dev.bytekv.proto.LogEntryOuterClass.LogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.bytekv.proto.LogEntryOuterClass.LogEntry other) {
        if (other == dev.bytekv.proto.LogEntryOuterClass.LogEntry.getDefaultInstance()) return this;
        if (other.getSerialNum() != 0L) {
          setSerialNum(other.getSerialNum());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getOperation().isEmpty()) {
          operation_ = other.operation_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (other.getIsTTL() != false) {
          setIsTTL(other.getIsTTL());
        }
        if (other.getExpiryTime() != 0L) {
          setExpiryTime(other.getExpiryTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serialNum_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                timestamp_ = input.readInt64();

                break;
              } // case 16
              case 26: {
                operation_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                key_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 42: {
                value_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 48: {
                isTTL_ = input.readBool();

                break;
              } // case 48
              case 56: {
                expiryTime_ = input.readInt64();

                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long serialNum_ ;
      /**
       * <code>int64 serialNum = 1;</code>
       * @return The serialNum.
       */
      @java.lang.Override
      public long getSerialNum() {
        return serialNum_;
      }
      /**
       * <code>int64 serialNum = 1;</code>
       * @param value The serialNum to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNum(long value) {
        
        serialNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 serialNum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialNum() {
        
        serialNum_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object operation_ = "";
      /**
       * <code>string operation = 3;</code>
       * @return The operation.
       */
      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operation = 3;</code>
       * @return The bytes for operation.
       */
      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operation = 3;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operation = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      /**
       * <code>string operation = 3;</code>
       * @param value The bytes for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 4;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 4;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 4;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 4;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 5;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private boolean isTTL_ ;
      /**
       * <code>bool isTTL = 6;</code>
       * @return The isTTL.
       */
      @java.lang.Override
      public boolean getIsTTL() {
        return isTTL_;
      }
      /**
       * <code>bool isTTL = 6;</code>
       * @param value The isTTL to set.
       * @return This builder for chaining.
       */
      public Builder setIsTTL(boolean value) {
        
        isTTL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isTTL = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsTTL() {
        
        isTTL_ = false;
        onChanged();
        return this;
      }

      private long expiryTime_ ;
      /**
       * <code>int64 expiryTime = 7;</code>
       * @return The expiryTime.
       */
      @java.lang.Override
      public long getExpiryTime() {
        return expiryTime_;
      }
      /**
       * <code>int64 expiryTime = 7;</code>
       * @param value The expiryTime to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryTime(long value) {
        
        expiryTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expiryTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiryTime() {
        
        expiryTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.bytekv.proto.LogEntry)
    }

    // @@protoc_insertion_point(class_scope:dev.bytekv.proto.LogEntry)
    private static final dev.bytekv.proto.LogEntryOuterClass.LogEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.bytekv.proto.LogEntryOuterClass.LogEntry();
    }

    public static dev.bytekv.proto.LogEntryOuterClass.LogEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntry>
        PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
      @java.lang.Override
      public LogEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.bytekv.proto.LogEntryOuterClass.LogEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dev_bytekv_proto_LogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dev_bytekv_proto_LogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/log_entry.proto\022\020dev.bytekv.prot" +
      "o\"\202\001\n\010LogEntry\022\021\n\tserialNum\030\001 \001(\003\022\021\n\ttim" +
      "estamp\030\002 \001(\003\022\021\n\toperation\030\003 \001(\t\022\013\n\003key\030\004" +
      " \001(\t\022\r\n\005value\030\005 \001(\t\022\r\n\005isTTL\030\006 \001(\010\022\022\n\nex" +
      "piryTime\030\007 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dev_bytekv_proto_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dev_bytekv_proto_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dev_bytekv_proto_LogEntry_descriptor,
        new java.lang.String[] { "SerialNum", "Timestamp", "Operation", "Key", "Value", "IsTTL", "ExpiryTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
